apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-killer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-killer
  template:
    metadata:
      labels:
        app: oom-killer
    spec:
      containers:
      - name: oom-killer
        image: polinux/stress
        resources:
          limits:
            memory: "50Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]