apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-image-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-image-demo
  template:
    metadata:
      labels:
        app: bad-image-demo
    spec:
      containers:
      - name: app
        image: nginx:latest
        ports:
        - containerPort: 80